<a href="https://colab.research.google.com/github/luiseduaardo/ml-ds/blob/main/supervised-learning/regressao_linear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import pandas as pd

df = pd.read_csv("Housing.csv")
df.sample(10)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
419,3360000,4960,4,1,3,no,no,no,no,no,0,no,semi-furnished
303,4200000,4500,3,1,1,yes,no,yes,no,no,0,no,furnished
428,3325000,4040,2,1,1,yes,no,no,no,no,1,no,unfurnished
418,3360000,3500,4,1,2,yes,no,no,no,yes,2,no,unfurnished
101,6230000,5500,3,1,3,yes,no,no,no,no,1,yes,unfurnished
500,2660000,2800,3,1,1,yes,no,no,no,no,0,no,unfurnished
357,3773000,6930,4,1,2,no,no,no,no,no,1,no,furnished
470,3010000,5076,3,1,1,no,no,no,no,no,0,no,unfurnished
6,10150000,8580,4,3,4,yes,no,no,no,yes,2,yes,semi-furnished
125,5943000,15600,3,1,1,yes,no,no,no,yes,2,no,semi-furnished

### Pré processamento

In [33]:
df['mainroad'] = df['mainroad'].apply(lambda x: 1 if x == 'yes' else 0)
df['guestroom'] = df['guestroom'].apply(lambda x: 1 if x == 'yes' else 0)
df['basement'] = df['basement'].apply(lambda x: 1 if x == 'yes' else 0)
df['hotwaterheating'] = df['hotwaterheating'].apply(lambda x: 1 if x == 'yes' else 0)
df['airconditioning'] = df['airconditioning'].apply(lambda x: 1 if x == 'yes' else 0)
df['prefarea'] = df['prefarea'].apply(lambda x: 1 if x == 'yes' else 0)

df['furnishingstatus'] = df['furnishingstatus'].apply(lambda x: 1 if x == 'furnished' else (0 if x == 'semi-furnished' else -1))

In [34]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,1
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,1
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,0
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,1
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,1

### Inferência

In [35]:
from sklearn.model_selection import train_test_split

X = df.drop(columns="price")
y = df["price"]

X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [36]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, Y_train)

LinearRegression()

In [37]:
predictions = model.predict(X_test)

In [38]:
from sklearn.metrics import mean_squared_error, confusion_matrix

mse = mean_squared_error(Y_test, predictions)
print(f"Mean Squared Error: {mse}")
print(f"Model Coefficient (Slope): {model.coef_}")
print(f"Model Intercept: {model.intercept_}")

Mean Squared Error: 1771751116594.0347
Model Coefficient (Slope): [2.35848772e+02 7.85744924e+04 1.09711727e+06 4.06223164e+05
 3.66824192e+05 2.33146766e+05 3.93159779e+05 6.87881311e+05
 7.85550579e+05 2.25756514e+05 6.29901661e+05 2.10397118e+05]
Model Intercept: 82685.95087911654

In [39]:
matriz = confusion_matrix(Y_test, predictions)
print(matriz)

ValueError: Classification metrics can't handle a mix of multiclass and continuous targets