<a href="https://colab.research.google.com/github/luiseduaardo/ml-ds/blob/main/supervised-learning/regressao_linear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [53]:
import pandas as pd

df = pd.read_csv("Housing.csv")
df.sample(10)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
361,3710000,6020,3,1,1,yes,no,no,no,no,0,no,semi-furnished
52,7350000,6000,4,2,4,yes,yes,no,no,yes,1,no,furnished
66,6930000,13200,2,1,1,yes,no,yes,yes,no,1,no,furnished
333,3920000,3000,3,1,2,yes,no,no,no,no,0,no,semi-furnished
520,2450000,7700,2,1,1,yes,no,no,no,no,0,no,unfurnished
284,4270000,7770,2,1,1,yes,no,no,no,no,1,no,furnished
174,5250000,3800,3,1,2,yes,yes,yes,no,no,1,yes,unfurnished
435,3290000,4040,2,1,1,yes,no,no,no,no,0,no,unfurnished
116,6020000,6900,3,2,1,yes,yes,yes,no,no,0,yes,unfurnished
256,4480000,4000,3,1,2,yes,no,no,no,no,2,no,furnished

### Pré processamento

In [54]:
binary_cols = ['mainroad', 'guestroom', 'basement', 'hotwaterheating', 'airconditioning', 'prefarea']
for col in binary_cols:
    df[col] = df[col].map({'yes': 1, 'no': 0})

df = pd.get_dummies(df, columns=['furnishingstatus'], drop_first=True)

In [55]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,False,False
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,False,False
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,True,False
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,False,False
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,False,False

In [56]:
from sklearn.model_selection import train_test_split

X = df.drop(columns="price")
y = df["price"]

X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [57]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

### Inferência

In [58]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, Y_train)

LinearRegression()

In [59]:
predictions = model.predict(X_test)

In [60]:
from sklearn.metrics import mean_squared_error, mean_absolute_error
from numpy import sqrt

mae = mean_absolute_error(Y_test, predictions)
rmse = sqrt(mean_squared_error(Y_test, predictions))

print(f"Root-Mean Squared Error: {rmse:.2f}")
print(f"Mean Absolute Error: {mae:.2f}")

Root-Mean Squared Error: 1324506.96
Mean Absolute Error: 970043.40

In [61]:
comp = pd.DataFrame({'parametro': df.columns[1:], "coefciente": model.coef_})
comp

                          parametro     coefciente
0                              area  519552.416340
1                          bedrooms   57349.559419
2                         bathrooms  521879.027748
3                           stories  349251.438906
4                          mainroad  128498.628215
5                         guestroom   88768.667686
6                          basement  187067.803214
7                   hotwaterheating  149862.702991
8                   airconditioning  365157.393851
9                           parking  192005.953667
10                         prefarea  266656.351993
11  furnishingstatus_semi-furnished  -62837.321865
12     furnishingstatus_unfurnished -192015.917982